# Generated by Django 3.2.9 on 2021-12-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='Total price')),
                ('products', models.ManyToManyField(to='Menu.Product', verbose_name='Products')),
            ],
        ),
    ]
