# Generated by Django 3.2.9 on 2021-12-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session',
            field=models.CharField(default='session id', max_length=350, verbose_name='Session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Total price'),
        ),
    ]
