# Generated by Django 4.0 on 2021-12-26 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
        ('Shopping_Cart', '0002_auto_20211202_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='QTY')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shopping_Cart.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.product')),
            ],
        ),
    ]
